### ISSUE TITLE
Having button pressed during start up causes issue at current draw selection

### ISSUE THREAD

**Issue by AlbertPhan** [Addy771/LoadTest#1] opened 2016-11-02 20:31 UTC
When you hold down the button and power it on it causes the current draw number to increment/decrement indefinitely (depending on what button was held on in the beginning. Pressing the button then causes it do the opposite function eg. decrements while held but increments when let go. This might be due to how the bounce2 library initializes the buttons.

**Comment by Addy771** [comment] 2017-01-09 00:54
Caused by bug in bounce2 library. Fixed as of 9d5592dbfb183ee4df030cfd5eed796e943d579e

**Closed as completed by Addy771** 2017-01-09 00:54 UTC
Labels: bug
